# Site settings
title: NahyeonCodingLog
email: naboee0627@gmail.com
description: >-
  My records diving into coding.
github_username: nh0627

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.22.0
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Author
author:
  name: Nahyeon Lee
  avatar: /assets/images/bio.png
  bio: Web DeveloperğŸ‘©â€ğŸ’»ğŸ’«
  location: Finland
  github: nh0627

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      toc: true
      toc_sticky: true
      toc_label: On this post 
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Search
search: true

# Archives
category_archive:
  type: liquid
  path: /categories/

# Files
include:
  - _pages